export const dobavitelji = {
    acord: {
        nodes: "podjetje.izdelki.izdelek",
        nodes1: "['podjetje']['izdelki']['izdelek']",
        file: "acord.xml",
        keys: ["EAN", "izdelekIme", "opis", "PPC", "nabavnaCena", "blagovnaZnamka", "kategorija", "slikaMala", "slikaVelika", "dobava"]
    },    
    // acordOriginal: {
    //     nodes: "podjetje.izdelki.izdelek",
    //     file: "acord.xml",
    //     attributes: {
    //         izdelekID,
    //         EAN,
    //         izdelekIme,
    //         url,
    //         opis,
    //         PPC,
    //         cenaAkcijska,
    //         nabavnaCena, 
    //         DC, 
    //         DRabat, 
    //         blagovnaZnamka, 
    //         dimenzijePaketa: [depth, height, width, grossWeight, netWeight], 
    //         davcnaStopnja, 
    //         kategorija, 
    //         slikaMala, 
    //         slikaVelika, 
    //         dobava, 
    //         spletnaStranProizvajalca,
    //         dodatneLastnosti: {},
    //     }
    // },
    // avtera: {
    //     nodes: "podjetje.izdelki.izdelek",
    //     file: "avtera.xml",
    //     attributes: {
    //         izdelekId,
    //         vendorItemNo,
    //         WarrantyCustomer,
    //         izdelekIme,
    //         opis,
    //         url,
    //         dodatneLastnosti: [],
    //         slikaVelika,
    //         dodatneSlike: [],
    //         PPC,
    //         cenaAkcijska,
    //         nabavnaCena,
    //         DC,
    //         davcnaStopnja,
    //         kategorija,
    //         blagovnaZnamka,
    //         skupinaIzdelka,
    //         dobava,
    //         zaloga,
    //         EAN,
    //         brutoDolzina,
    //         brutoSirina,
    //         brutoVisina,
    //         brutoTeza,
    //         eprelId
    //     }
    // },
    // colby: {
    //     nodes: "podjetje.izdelek",
    //     file: "colby.xml",
    //     attributes: {
    //         izdelekEAN,
    //         produktnaKoda,
    //         zaloznik,
    //         razvijalec,
    //         sifraDobavitelja,
    //         izdelekIme,
    //         naziv2,
    //         model,
    //         url,
    //         kratkiOpis,
    //         tehničniOpis,
    //         dodatneLastnosti,
    //         slikaVelika,
    //         slikaMala,
    //         dodatneSlike: [],
    //         slikaŠkatla,
    //         cena,
    //         cenaAkcijska,
    //         PPCcena,
    //         davcnaStopnja,
    //         garancija,
    //         netoTeza,
    //         brutoTeza,
    //         kategorija,
    //         blagovnaZnamka,
    //         URLTehnicneProizvajalca,
    //         navodila,
    //         dobava,
    //         zaloga
    //     }
    // },
    // elkotex: {
    //     nodes: "items.item",
    //     file: "elkotex.xml",
    //     attributes: {
    //         ident,
    //         stevilka,
    //         naziv,
    //         opis,
    //         slike: [],
    //         price,
    //         rabat,
    //         zaloga,
    //         kategorijaID,
    //         kategorijaNaziv,
    //         mpc,
    //         garancija,
    //         rokDobave,
    //         ean,
    //         znamkaId,
    //         visina,
    //         sirina,
    //         globina,
    //         brutoTeza,
    //         davek,
    //     }
    // },
    // eventus: {
    //     nodes: "podjetje.izdelki.izdelek",
    //     file: "eventus.xml",
    //     attributes: {
    //         izdelekId,
    //         sifraBar,
    //         sifraSku,
    //         EAN,
    //         izdelekIme,
    //         url,
    //         kratekOpis,
    //         opis,
    //         dodatneLastnosti: [],
    //         slikaVelika,
    //         dodatneSlike: [],
    //         PPC,
    //         nabavnaCena,
    //         DC,
    //         davcnaStopnja,
    //         kategorija,
    //         blagovnaZnamka,
    //         dobava,
    //         garancija,
    //         brutoDolzina,
    //         brutoSirina,
    //         brutoVisina,
    //         brutoTeza
    //     }
    // }
}

// asbis1: {
//     nodes: "ProductCatalog.Product",
//     file: "./XML/asbis1.xml",
//     attributes: {
//         productCode,
//         vendor,
//         productType,
//         productCategory,
//         productDescription,
//         image,
//         productCard,
//         attrList: {},
//         images: []
//     }
// },
// asbis2: {
//     nodes: "CONTENT.PRICES.PRICE",
//     file: "./XML/asbis2.xml",
//     attributes: {
//         WIC,
//         description,
//         vendorName,
//         groupName,
//         vpfName,
//         currencyCode,
//         avail,
//         myPrice,
//         warrantyTerm,
//         groupId,
//         vendorId,
//         smallImage,
//         productCard,
//         EAN
//     }
// },