import cn from "./categoryNames.js";

const acordCategoryNames = {
	[cn.AUDIO_VIDEO]: ["Avdio/Video"],
	[cn.POWERLINE]: ["Vtičnice"],
	[cn.LAN_CARD_EXTENDERS]: ["Mrežne kartice in adapterji", "WiFi ojačevalci - extender", "Antene"],
	[cn.ROUTER_SWITCH_AP]: ["Centralne enote", "Stikala - switch", "Usmerjevalniki - router", "Dostopne točke - AP"],
	[cn.HDD]: ["Razširitvene kartice", "Trdi diski in SSD", "Zunanja ohišja za diske", "Zunanji trdi diski in SSD"],
	[cn.SOFTWARE]: ["Pisarniški programi", "Operacijski sistemi", "Druga programska oprema"],
	[cn.MONITOR]: ["Vgradni - OPS", "Interaktivni - touch", "Računalniški - desktop", "Informacijski - public"],
	[cn.WEB_CAM]: ["Kamere"],
	[cn.SD_CARD]: ["Spominske kartice", "Hubi, čitalci, priklopne postaje"],
	[cn.P_DOM]: ["Stikala", "Senzorji"],
	[cn.Z_RAZVLAZILEC]: ["Čistilci zraka"],
	[cn.P_VRT]: ["Krmilniki"],
	[cn.KONF_OPREMA]: ["Interaktivna oprema"],
	[cn.PC]: ["Namizni - desktop", "Dodatna interaktivna oprema", "Računalniki"],
	[cn.LAPTOP]: ["Prenosni - notebook"],
	[cn.NAS]: ["NAS strežniki"],
	[cn.SERVER]: ["Strežniki- server"],
	[cn.UPS]: ["UPS napajanja, inverterji, regulatorji napetosti", "Razdelilci in prenapetostna zaščita", "Prenapetostne zaščite"],
	[cn.SUR_KAMERE]: ["IP kamere", "Nadzorne kamere"],
	[cn.MINI_PC]: ["Mini, micro, barebone"],
	[cn.TABLET]: ["Tablični - tablet"],
	[cn.STOL]: ["Gaming stoli in mize"],
	[cn.AIO]: ["All-in-one - AIO"],
	[cn.GAMEPAD]: ["Igričarski pripomočki", "Igračarski pripomočki"],
	[cn.M_PODLOGE]: ["Gaming miške in podloge"],
	[cn.SCANNER]: ["Čitalniki črtnih kod"],
	[cn.POS]: ["Dodatna oprema za omare"],
	[cn.SUR_RECS]: ["Mrežni video snemalniki"],
	[cn.USB_KEY]: ["USB ključi"],
}

export default acordCategoryNames;