const acordCategoryMap = {
	"Zvok in slika": ["Avdio/Video"],
	"Powerline": ["Vtičnice"],
	"Igralni pripomočki": ["Igračarski pripomočki"],
	"Mrežne kartice, antene, WIFI ojačevalci": ["Mrežne kartice in adapterji", "WiFi ojačevalci - extender", "Antene"],
	"Usmerjevalniki, stikala in AP": ["Centralne enote", "Stikala - switch", "Usmerjevalniki - router", "Dostopne točke - AP"],
	"Trdi diski": ["Razširitvene kartice", "Trdi diski in SSD", "Zunanja ohišja za diske", "Zunanji trdi diski in SSD"],
	"Programska oprema": ["Pisarniški programi", "Operacijski sistemi"],
	"Monitorji": ["Vgradni - OPS", "Interaktivni - touch", "Računalniški - desktop", "Informacijski - public"],
	"Spletne kamere": ["Kamere"],
	"Spominske kartice in čitalci": ["Spominske kartice"],
	"Naprave za pametni dom": ["Stikala", "Senzorji"],
	"Razvlažilci zraka": ["Čistilci zraka"],
	"Pametni vrtovi": ["Krmilniki"],
	"Konferenčna oprema": ["Interaktivna oprema"],
	"Računalniki": ["Namizni - desktop", "Dodatna interaktivna oprema"],
	"Prenosniki": ["Prenosni - notebook"],
	"NAS sistemi": ["NAS strežniki"],
	"Strežniki": ["Strežniki- server"],
	"Brezprekinitveni napajalniki": ["UPS napajanja, inverterji, regulatorji napetosti", "Razdelilci in prenapetostna zaščita"],
	"Kamere": ["IP kamere", "Nadzorne kamere"],
	"Mini": ["Mini, micro, barebone"],
	"Tablični računalniki": ["Tablični - tablet"],
	"Gaming stoli": ["Gaming stoli in mize"],
	"All in one": ["All-in-one - AIO"],
	"Spominske kartice in čitalci": ["Hubi, čitalci, priklopne postaje"],
	"Igralni pripomočki": ["Igričarski pripomočki"],
	"Podloge": ["Gaming miške in podloge"],
	"Optični bralniki": ["Čitalniki črtnih kod"],
	"POS in dodatki": ["Dodatna oprema za omare"],
}

export default acordCategoryMap;