const asbisCategoryMap = {
	"Mrežne kartice, antene, WIFI ojačevalci": [
		"Antenna",
		"Networking - Accessories",
		"Networking - Cloud Keys & Gateways - Cloud Key Enterprise",
		"Network Management Module",
		"Network Interface Card",
		"Networking - Range Extender",
	],
	"Usmerjevalniki, stikala in AP": [
		"Networking - Router",
		"Networking - Transceiver",
		"Networking - Wireless Outdoor Access Point",
		"Networking - Wireless Access Point",
		"Network Switch",
	],
	Snemalniki: ["Security - Surveillance Video Recorder"],
	Sesalniki: [
		"Vacuum Cleaner Robot",
		"Vacuum Cleaner Stick",
		"Vacuum Cleaner Transformer",
		"Acc - Vacuum Cleaners",
	],
	"NAS sistemi": ["Memory NAS", "NAS Accessories", "Desktop NAS", "Rack NAS"],
	Mešalniki: ["Acc - Blenders", "Hand Blender"],
	"Trdi diski": [
		"SSD NAS",
		"HDD NAS",
		"HDD/SSD Enclosure",
		"HDD Video Surveillance",
		"HDD Server",
		"HDD External",
		"HDD Mobile",
		"HDD Desktop",
		"SSD strežniški diski",
		"SSD diski",
		"SSD External",
		"HDD Cabinet",
	],
	Domofoni: ["Intercom Panel"],
	"Naprave za pametni dom": [
		"Liquidaiser",
		"Irrigators",
		"Solar Panel",
		"Pametni senzorji",
		"Smart Heaters",
	],
	"Optične enote": [
		"ODD Blu-RAY Writers",
		"ODD DVD-RW External Slim",
		"ODD Blu-ray Writer External Desktop",
		"ODD DVD-RW",
	],
	"Gaming stoli": ["Gaming Chair", "Gaming Desk"],
	"HI-FI in prenosni zvočniki": [
		"Multimedia - Speaker Wi-Fi",
		"Multimedia - Speaker Bluetooth",
		"Multimedia - Audio System",
		"Multimedia - Speaker",
	],
	"Ustna nega": ["Acc - Dental care", "Ščetke za zobe"],
	"Tablični računalniki": ["IPad Accessories"],
	Slušalke: [
		"TWS Bluetooth Headsets",
		"Multimedia - Headset",
		"Multimedia - PC Headsets",
		"Bluetooth Headset",
		"Gaming Headset",
	],
	"Spletne kamere": ["Web Camera", "VC WebCams"],
	Strežniki: ["Server Desktop", "Main Board Server"],
	Procesorji: ["CPU Desktop"],
	"Konferenčna oprema": ["Video Conferencing Solution"],
	"Programska oprema": ["Software Electronic Keys", "Soft OEM. MS OS for PC"],
	Monitorji: ["Zaslon velikega formata", "LED monitor"],
	Mini: ["PC NetTop", "PC Barebone"],
	Napajalniki: ["Power Supply Unit"],
	Ohišja: ["PC Chassis"],
	"Dodatki za prenosnike": [
		"Torbica za prenašanje",
		"Cooling stand for Notebook",
	],
	Hlajenje: ["Cooling System"],
	Miške: [
		"Input Devices - Mouse Box",
		"Input Devices - Mouse",
		"Input Devices - Pointing Device Box",
		"Gaming Mouse",
		"Gaming Mousepads",
	],
	Tipkovnice: [
		"Input Devices - Keyboard Box",
		"Input Devices - Keyboard",
		"Gaming Keyboard",
	],
	"Osnovne plošče": ["Osnovna plošča za namizni računalnik"],
	Pomnilniki: [
		"Memory Gaming Desktop",
		"Memory ( Server )",
		"Memory ( Mobile )",
		"Memory ( Desktop )",
	],
	"Razvlažilci zraka": ["Acc - Air Purifiers", "Čistilci zraka"],
	Podloge: ["Mouse Pad"],
	"Grafične kartice": ["Graphics Processing Unit", "Video Card"],
	"Gaming pripomočki": [
		"Gaming Controller",
		"Gaming Accessories",
		"Gaming Microphone",
		"Gaming pripomočki",
	],
	Kamere: ["Security - Surveillance System Accessories", "IP Camera"],
	Televizije: ["LED TV"],
	Žari: ["Acc - Multibakers/Grills", "Grills"],
	"Vakumski aparati": ["Vacuum Sealers"],
	"Nega las": ["Feni za lase", "Hair Stylers"],
	"Priprava kave in čaja": ["Kavni aparati"],
	"Pripomočki za osebno nego": ["Tehtnice za kopalnico"],
	"Čistilci na tlak in metle": [
		"Acc - Steam Mops",
		"Steam Mops",
		"Cleaning Articles",
	],
	Kuhalniki: ["Sous-Vide", "Kuhalniki na paro"],
	Tehtnice: ["Kuhinjske tehtnice"],
	"Športne ure": ["Plates and ovens", "Otroška ura", "Pametna ura"],
	"Kuhinjski roboti": ["Robot Kitchen"],
};

export default asbisCategoryMap

