import cn from "./categoryNames.js";

const asbisCategoryMap = {
	[cn.LAN_CARD_EXTENDERS]: [
		"Antenna",
		"Networking - Accessories",
		"Networking - Cloud Keys & Gateways - Cloud Key Enterprise",
		"Network Management Module",
		"Network Interface Card",
		"Networking - Range Extender",
	],
	[cn.ROUTER_SWITCH_AP]: [
		"Networking - Router",
		"Networking - Transceiver",
		"Networking - Wireless Outdoor Access Point",
		"Networking - Wireless Access Point",
		"Network Switch",
	],
	[cn.SUR_RECS]: ["Security - Surveillance Video Recorder"],
	[cn.SESALEC]: [
		"Vacuum Cleaner Robot",
		"Vacuum Cleaner Stick",
		"Vacuum Cleaner Transformer",
		"Acc - Vacuum Cleaners",
	],
	[cn.NAS]: ["Memory NAS", "NAS Accessories", "Desktop NAS", "Rack NAS"],
	[cn.MESALNIK]: ["Acc - Blenders", "Hand Blender"],
	[cn.HDD]: [
		"SSD NAS",
		"HDD NAS",
		"HDD/SSD Enclosure",
		"HDD Video Surveillance",
		"HDD Server",
		"HDD External",
		"HDD Mobile",
		"HDD Desktop",
		"SSD strežniški diski",
		"SSD diski",
		"SSD External",
		"HDD Cabinet",
	],
	[cn.SUR_DOMOFON]: ["Intercom Panel"],
	[cn.P_DOM]: [
		"Liquidaiser",
		"Irrigators",
		"Solar Panel",
		"Pametni senzorji",
		"Smart Heaters",
	],
	[cn.ROM_DRIVE]: [
		"ODD Blu-RAY Writers",
		"ODD DVD-RW External Slim",
		"ODD Blu-ray Writer External Desktop",
		"ODD DVD-RW",
	],
	[cn.STOL]: ["Gaming Chair", "Gaming Desk"],
	[cn.HIFI]: [
		"Multimedia - Speaker Wi-Fi",
		"Multimedia - Speaker Bluetooth",
		"Multimedia - Audio System",
		"Multimedia - Speaker",
	],
	[cn.N_USTNA]: ["Acc - Dental care", "Ščetke za zobe"],
	[cn.TABLET]: ["IPad Accessories"],
	[cn.SLUSALKE]: [
		"TWS Bluetooth Headsets",
		"Multimedia - Headset",
		"Multimedia - PC Headsets",
		"Bluetooth Headset",
		"Gaming Headset",
	],
	[cn.WEB_CAM]: ["Web Camera", "VC WebCams"],
	[cn.SERVER]: ["Server Desktop", "Main Board Server"],
	[cn.CPU]: ["CPU Desktop"],
	[cn.KONF_OPREMA]: ["Video Conferencing Solution"],
	[cn.SOFTWARE]: ["Software Electronic Keys", "Soft OEM. MS OS for PC"],
	[cn.MONITOR]: ["Zaslon velikega formata", "LED monitor"],
	[cn.MINI_PC]: ["PC NetTop", "PC Barebone"],
	[cn.PSU]: ["Power Supply Unit"],
	[cn.OHISJE]: ["PC Chassis"],
	[cn.LAPTOP_DODATKI]: [
		"Torbica za prenašanje",
		"Cooling stand for Notebook",
	],
	[cn.COOLER]: ["Cooling System"],
	[cn.MIS]: [
		"Input Devices - Mouse Box",
		"Input Devices - Mouse",
		"Input Devices - Pointing Device Box",
		"Gaming Mouse",
		"Gaming Mousepads",
	],
	[cn.TIPKOVNICA]: [
		"Input Devices - Keyboard Box",
		"Input Devices - Keyboard",
		"Gaming Keyboard",
	],
	[cn.M_BOARD]: ["Osnovna plošča za namizni računalnik"],
	[cn.RAM]: [
		"Memory Gaming Desktop",
		"Memory ( Server )",
		"Memory ( Mobile )",
		"Memory ( Desktop )",
	],
	[cn.Z_RAZVLAZILEC]: ["Acc - Air Purifiers", "Čistilci zraka"],
	[cn.M_PODLOGE]: ["Mouse Pad"],
	[cn.GPU]: ["Graphics Processing Unit", "Video Card"],
	[cn.GAMEPAD]: [
		"Gaming Controller",
		"Gaming Accessories",
		"Gaming Microphone",
		"Gaming pripomočki",
	],
	[cn.SUR_KAMERE]: ["Security - Surveillance System Accessories", "IP Camera"],
	[cn.TV]: ["LED TV"],
	[cn.ZAR]: ["Acc - Multibakers/Grills", "Grills"],
	[cn.VAKUUM]: ["Vacuum Sealers"],
	[cn.N_LAS]: ["Feni za lase", "Hair Stylers"],
	[cn.KAVA_CAJ]: ["Kavni aparati"],
	[cn.N_ACC]: ["Tehtnice za kopalnico"],
	[cn.VAP]: [
		"Acc - Steam Mops",
		"Steam Mops",
		"Cleaning Articles",
	],
	[cn.K_PLOSCA]: ["Sous-Vide", "Kuhalniki na paro"],
	[cn.TEHTNICA]: ["Kuhinjske tehtnice"],
	[cn.URE]: ["Plates and ovens", "Otroška ura", "Pametna ura"],
	[cn.K_ROBOT]: ["Robot Kitchen"],
};

export default asbisCategoryMap

