const avteraCategoryMap = {
			Televizije: [
				"LED hotelski televizorji",
				"LED TV",
				"LED prikazovalniki",
			],
			"Domači kino": ["Hišni Kino"],
			"Tablični računalniki": ["Elektronski bralniki in dodatki"],
			Zamrzovalniki: ["Hladilne skrinje"],
			"Spominske kartice in čitalci": [
				"Čitalci kartic",
				"Spominske kartice",
			],
			Monitorji: ["LCD monitorji"],
			"Usmerjevalniki, stikala in AP": [
				"Mrežna oprema",
				"Mrežna oprema-brezžična",
			],
			"Potrošni material": ["Bobni"],
			"Dodatki za fotoaparate": ["Dodatki Foto/Video"],
			Tiskalniki: ["'Dodatki za tiskalnike", "Multifunkcijske naprave"],
			"POS in dodatki": ["POS sistemi", "Dodatki za kopirne stroje"],
			"Dodatki za prenosnike": [
				"Dodatki za računalnike",
				"Torbice in ovitki za tablice",
				"Dodatki za tablice",
			],
			"Optični bralniki": ["Čitalniki"],
			Strežniki: ["Tiskalniški strežniki"],
			"Optične enote": ["Optični pogoni"],
			"Trdi diski": ["SSD"],
			Fotoaparati: ["Digitalni fotoaparati"],
			"Zvok in slika": ["Avdio"],
			"Programska oprema": [
				"DSP programska oprema",
				"FPP za podjetja in domačo up.",
			],
			"Konferenčna oprema": [
				"Komunikacijske rešitve",
				"Avdio konferenčni sistemi",
				"Video konferenčni sistemi",
			],
			"All in one": ["Consumer AIO", "Računalniki - All in One"],
			Kuhališča: ["Plinske kuhane plošče", "Električne kuhalne plošče"],
			Pečice: ["Električne pečice"],
			Prenosniki: [
				"Consumer zmogljivi (Envy, Spectre, Omnibook)",
				"Consumer gaming (Omen, Victus)",
				"Consumer osnovni (Laptop, Pavilion, X360)",
				"Prenosniki - poslovni",
				"Prenosniki - zmogljivi",
				"Prenosniki - gaming",
				"Prenosniki - delovne postaje",
				"Prenosniki - osnovni",
				"Prenosniki - hibridni 2 v 1",
			],
			"Šport in prosti čas": [
				"Elektični skuterji",
				"Dodatki za skiroje",
				"Električna kolesa",
				"Tekalna steza",
				"Veslaška naprava",
			],
			"Namizni računalniki": [
				"Računalniki - zmogljivi",
				"Računalniki - delovne postaje",
				"Računalniki - poslovni",
			],
			Čelade: ["Mestne čelade"],
			"Športne ure": ["Nosljive naprave"],
			"Hlajenje in gretje": ["Električna ogrevala"],
		};

export default avteraCategoryMap;