const categoryNames = Object.freeze({
	// RAČUNALNIŠTVO
	LAPTOP: "Prenosniki",
	LAPTOP_DODATKI: "Dodatki za prenosnike",
	AIO: "All in One",
	PC: "Namizni računalniki",
	MINI_PC: "Mini",
	TABLET: "Tablični računalniki",
	SERVER: "Strežniki",
	NAS: "NAS sistemi",
	MONITOR: "Monitorji",
	// KOMMPONENTE
	M_BOARD: "Osnovne plošče",
	CPU: "Procesorji",
	RAM: "Pomnilniki",
	HDD: "Trdi diski",
	OHISJE: "Ohišja",
	PSU: "Napajalniki",
	GPU: "Grafične kartice",
	ROM_DRIVE: "Optične enote",
	ZVOČNA_KARTICA: "Zvočne kartice",
	COOLER: "Hlajenje",
	// MREŽNA OPREMA
	ROUTER_SWITCH_AP: "Usmerjevalniki, stikala in AP",
	LAN_CARD_EXTENDERS: "Mrežne kartice, antene WIFI ojačevalci",
	POWERLINE: "Powerline",
	// TISKANJE IN OPTIČNO BRANJE
	PRINTER: "Tiskalniki",
	SCANNER: "Optični bralniki",
	POS: "POS in dodatki",
	POTROSNI_M: "Potrošni material",
	// ZUNANJE NAPRAVE
	TIPKOVNICA: "Tipkovnice",
	MIS: "Miške",
	M_PODLOGE: 'Podloge',
	KOMPLET: "Kompleti",
	SLUSALKE: "Slušalke",
	ZVOČNIK: "Zvočniki",
	WEB_CAM: "Spletne kamere",
	USB_KEY: "USB ključki",
	SD_CARD: "Spominske kartice in čitalci",
	EXT_MEDIA: "Mediji",
	UPS: "Brezprekinitveno napajanje",
	KONF_OPREMA: "Konferenčna oprema",
	// GAMING
	KONZOLE: "Konzole",
	IGRE: "Igre",
	GAMEPAD: "Igralni pripomočki",
	STOL: "Gaming stoli",
	// SOFTWARE
	SOFTWARE: "Programska oprema",
	// KRIPTO SVET
	CRYPTO: "Kripto svet",
	C_WALLET: "Denarnice",
	// ZZVOK IN SLIKA
	AUDIO_VIDEO: "Zvok in slika",
	TV: "Televizije",
	TV_MOUNT: "Nosilci za TV",
	FOTOAPARAT: "Fotoaparati",
	LENS: "Objektivi",
	RADIO: "Radio in budilke",
	HIFI: "HI-FI in Prenosni zvočniki",
	SOUND_BAR: "Domači kino",
	// VIDEO NADZOR
	SUR_RECS: "Snemalniki",
	SUR_KAMERE: "Kamere",
	SUR_DOMOFON: "Domofoni",
	SUR_MONITOR: "Monitorji",
	SUR_ACC: "Nosilci in napajalniki",
	// PROJEKCIJA
	PROJ: "Projektorji",
	PROJ_PLATNO: "Projekcijska platna",
	PROJ_NOSILEC: "Nosilci za projektorje",
	PROJ_ZARNICA: "Žarnice za projektorje",
	// BELA TEHNIKA
	PRALNI: "Pralni stroji",
	SUSILNI: "Sušilni stroji",
	PRALNO_SUŠILNI: "Pralno sušilni stroji",
	POMIVALNI: "Pomivalni stroji",
	HLADILNIK: "Hladilniki",
	ZAMRZOVALNIK: "Zamrzovalniki",
	K_PECICA: "Pečice",
	K_PLOSCA: "Kuhališča",
	K_SETI: "Kuhalni seti",
	K_STEDILNIK: "Štedilniki",
	K_NAPA: "Nape",
	// MALI GOSPODINJSKI APARATI
	MIKROVALOVNA: "Mikrovalovne pečice",
	MESO_SALAMOREZNICA: "Mesoreznice in salamoreznice",
	CVRTNIK: "Cvrtniki",
	KUHALNIK: "Kuhalniki",
	GRELNIK_V: "Grelniki vode",
	K_ROBOT: "Kuhinjski roboti",
	K_ZAR: "Kuhinjski žari",
	MESALNIK: "Mešalniki",
	TOASTER: "Opekači kruha",
	SOK_OŽEM: "Sokovniki in ožemalniki",
	PEKA_KRUH: "Aparati za peko kruha",
	VAKUUM: "Vakuumski aparati",
	MULTIPRAKTIK: "Multipraktiki",
	KAVA_CAJ: "Priprava kave in čaja",
	SUSILEC_SADJA: "Sušilci sadja",
	POSODA: "Posoda",
	PREN_KUH: "Prenosna kuhališča",
	LEDOMAT: "Ledomati",
	TEHTNICA: "Tehtnice",
	LIKALNIK: "Likalniki",
	SESALEC: "Sesalniki",
	// HLAJENJE IN GRETJE
	KLIMA: "Klime",
	VENTILATOR: "Ventilatorji",
	RADIATOR: "Radiatorji",
	Z_RAZVLAZILEC: "Razvlažilci zraka",
	Z_VLAZILEC: "Vlažilci zraka",
	BOJLER: "Bojlerji",
	TOPLOTNA_C: "Toplotne črpalke",
	HRANILNIK_V: "Hranilniki vode",
	// DOM IN VRT
	DOM_VRT: "Dom in vrt",
	ZAR: "Žari",
	P_DOM: "Naprave za pametni dom",
	P_VRT: "Pametni vrtovi",
	SEME: "Semena",
	// OSEBNA NEGA
	N_BRIVNIK: "Brivniki",
	N_REZNIK: "Strižniki",
	N_LAS: "Nega las",
	N_DEPILATOR: "Depilatorji in epilatorji",
	N_USTNA: "Ustna nega",
	N_ACC: "Pripomočki za ustno nego",
	// ŠPORT IN PROSTI ČAS
	DALJNOGLED: "Daljnogledi",
	KOLO: "Kolesa in skuterji",
	DRON: "Droni in dodatki",
	CELADA: "Čelade",
	URE: "Športne ure",
	CAMP: "Kampiranje",
	H_TORBA: "Hladilne torbe",
	TERMOVKA: "Termovke",
	VAP: "Čistilci na tlak in metle",
});

export default categoryNames;