import cn from "./categoryNames.js";

const elkotexCategoryMap = {
	[cn.ZVOČNA_KARTICA]: ["Razširitvene kartice"],
	[cn.LIKALNIK]: ["Likalniki", "Likalniki in likalne mize"],
	[cn.N_USTNA]: ["Nega zob"],
	[cn.N_ACC]: ["Nega telesa"],
	[cn.POS]: [
		"Pisarniška tehnika",
		"Uničevalci dokumentov",
		"Organizatorji in dodatki",
	],
	[cn.PRINTER]: ["Laserski tiskalniki"],
	[cn.EXT_MEDIA]: ["Bluetooth", "USB hubi in priklopne postaje", "Centralne nadzorne enote (HUB)", "MP3/MP4 predvajalniki"],
	[cn.LAN_CARD_EXTENDERS]: [
		"Ojačevalniki brezžičnega omrežja",
		"PoE",
		"Mrežne kartice",
	],
	[cn.Z_VLAZILEC]: ["Difuzorji", "Vlažilniki zraka"],
	[cn.FOTOAPARAT]: ["Torbe in nahrbtniki za fotoaparate in drone"],
	[cn.URE]: ["Pametne ure"],
	[cn.SESALEC]: [
		"Klasični in ročni sesalniki",
		"Pokončni sesalniki",
		"Parni čistilniki",
	],
	[cn.HIFI]: ["Prenosni zvočniki"],
	[cn.P_DOM]: [
		"Domofoni",
		"Vremenske postaje",
		"Pametne sijalke",
		"Robotski sesalniki",
		"Robotske kosilnice",
		"Pametni dom",
		"Pametne vtičnice",
		"Senzorji",
	],
	[cn.ROUTER_SWITCH_AP]: [
		"Krmilniki in stikala",
		"Stikala",
		"Usmerjevalniki",
	],
	[cn.VENTILATOR]: ["Ventilatorji in dodatki"],
	[cn.MINI_PC]: ["Mini-micro-barebone (NUC)"],
	[cn.LAPTOP_DODATKI]: [
		"Torbe za prenosnike",
		"Nahrbtniki za prenosnike",
		"Hlajenje za prenosnike",
		"Dodatki za tablične računalnike",
	],
	[cn.RADIATOR]: ["Oljni radiatorji", "Konvekcijski radiatorji"],
	[cn.SLUSALKE]: [
		"Slušalke in mikrofoni",
		"Naglavne slušalke",
		"True Wireless slušalke",
		"In-Ear slušalke",
	],
	// "Mali gospodinjski aparati": [
	// 	"Kuhinjsko orodje",
	// 	"Kuhinjski organizatorji",
	// 	"Kuhinjski pripomočki",
	// 	"Priprava hrane",
	// ],
	[cn.SOUND_BAR]: ["Zvočni sistemi za domači kino", "Medijski predvajalniki"],
	[cn.TABLET]: [
		"Tablični računalniki in e-Bralniki",
		"Etuiji za tablice in diske",
	],
	[cn.CAMP]: ["Torbe in nahrbtniki za prosti čas"],
	[cn.P_DOM]: [
		"Pametne zapestnice",
		"Pametni telefoni",
		"Nosilci za telefone",
		"Prenosne baterije / Powerbank",
	],
	[cn.KOLO]: [
		"Dodatki za skiroje",
		"Električni skiroji",
		"Vse za kolo",
	],
	[cn.GRETJE]: [
		"IR grelniki",
		"Kaloriferji, stenski grelniki",
		"Kamini",
		"Solarni paneli",
	],
	[cn.HLAJENJE]: ["Hladilci zraka"],
	[cn.SOFTWARE]: ["Microsoft Windows", "Microsoft Office"],
	[cn.POWERLINE]: ["Home Plug PowerLine"],
	[cn.NAS]: ["NAS naprave", "NAS dodatki"],
	[cn.HLAJENJE]: ["Hladilniki za procesorje", "Termalne paste"],
	[cn.KAVA_CAJ]: ["Mlinčki za kavo", "Kavni aparati"],
	[cn.HDD]: ["Zunanji diski", "Zunanji SSD diski", "SSD diski"],
	[cn.POTROSNI_M]: ["Tonerji in črnila", "Papir"],
	[cn.SD_CARD]: [
		"Spominske kartice",
		"Čitalniki kartic in zaščitne škatlice",
	],
	[cn.RAM]: ["Pomnilniški moduli"],
	[cn.PEKA_KRUH]: ["Opekači kruha, toasterji"],
	[cn.LEDOMAT]: ["Priprava sladoleda in ledomati"],
	[cn.TEHTNICA]: ["Kuhinjske tehtnice"],
	[cn.MESO_SALAMOREZNICA]: ["Salamoreznice/mletje mesa"],
	[cn.MESALNIK]: ["Blenderji, mešalniki", "Penilniki mleka"],
	[cn.POSODA]: ["Posode za živila", "Kuhinjska posoda", "Posodice za vodo"],
	[cn.K_ZAR]: ["Električne pečice, žari in grelne ploskve"],
	[cn.DOM_VRT]: [
		"Stojala za perilo in obešalniki",
		"Vrtno orodje",
		"Ročno orodje",
		"Hišni polnilci",
		"Čiščenje okolice",
		"Oprema za delavnice, skladišča",
		"Senčniki in paviljoni",
		"Oprema vrta in okolice",
	],
	[cn.RADIO]: ["Radio/Gramofoni"],
	[cn.ZAR]: ["Kamp žari", "Žari in kurišča"],
	[cn.CAMP]: [
		"Prenosne svetilke",
		"Termovke",
		"Kamp dodatki in ostalo",
		"Kamp hladilne skrinje in torbe",
		"Kamp svetilke in komarniki",
		"Kamp paviljoni, šotori, senčniki",
		"Kamp pohištvo",
		"Kamp ležalniki in stoli",
		"Kamp kuhinjski pripomočki",
	],
	[cn.UPS]: ["Brezprekinitvena napajanja"],
};

export default elkotexCategoryMap;
