const elkotexCategoryMap = {
	Komponenta: ["Razširitvene kartice"],
	Likalniki: ["Likalniki", "Likalniki in likalne mize"],
	"Ustna nega": ["Nega zob"],
	"Pripomočki za osebno nego": ["Nega telesa"],
	"POS in dodatki": [
		"Pisarniška tehnika",
		"Uničevalci dokumentov",
		"Organizatorji in dodatki",
	],
	Tiskalniki: ["Laserski tiskalniki"],
	Mediji: ["Bluetooth"],
	"Mrežne kartice, antene, WIFI ojačevalci": [
		"Ojačevalniki brezžičnega omrežja",
		"PoE",
		"Mrežne kartice",
	],
	"Vlažilci zraka": ["Difuzorji", "Vlažilniki zraka"],
	Fotoaparati: ["Torbe in nahrbtniki za fotoaparate in drone"],
	"Športne ure": ["Pametne ure"],
	Sesalniki: [
		"Klasični in ročni sesalniki",
		"Pokončni sesalniki",
		"Parni čistilniki",
	],
	"HI-FI in Prenosni zvočniki": ["Prenosni zvočniki"],
	"Naprave za pametni dom": [
		"Domofoni",
		"Vremenske postaje",
		"Pametne sijalke",
		"Robotski sesalniki",
		"Robotske kosilnice",
		"Pametni dom",
		"Pametne vtičnice",
		"Senzorji",
	],
	"Usmerjevalniki, stikala in AP": [
		"Krmilniki in stikala",
		"Stikala",
		"Usmerjevalniki",
	],
	Ventilatorji: ["Ventilatorji in dodatki"],
	Mini: ["Mini-micro-barebone (NUC)"],
	"Dodatki za prenosnike": [
		"Torbe za prenosnike",
		"Nahrbtniki za prenosnike",
		"Hlajenje za prenosnike",
		"Dodatki za tablične računalnike",
	],
	Radiatorji: ["Oljni radiatorji", "Konvekcijski radiatorji"],
	Slušalke: [
		"Slušalke in mikrofoni",
		"Naglavne slušalke",
		"True Wireless slušalke",
		"In-Ear slušalke",
	],
	"Zunanje naprave": [
		"USB hubi in priklopne postaje",
		"Centralne nadzorne enote (HUB)",
	],
	"Mali gospodinjski aparati": [
		"Kuhinjsko orodje",
		"Kuhinjski organizatorji",
		"Kuhinjski pripomočki",
		"Priprava hrane",
	],
	"Domači kino": ["Zvočni sistemi za domači kino", "Medijski predvajalniki"],
	"Tablični računalniki": [
		"Tablični računalniki in e-Bralniki",
		"Etuiji za tablice in diske",
	],
	"Šport in prosti čas": ["Torbe in nahrbtniki za prosti čas"],
	"Pametne naprave": [
		"MP3/MP4 predvajalniki",
		"Pametne zapestnice",
		"Pametni telefoni",
		"Nosilci za telefone",
		"Prenosne baterije / Powerbank",
	],
	"Kolesa in skuterji": [
		"Dodatki za skiroje",
		"Električni skiroji",
		"Vse za kolo",
	],
	"Hlajenje in gretje": [
		"IR grelniki",
		"Hladilci zraka",
		"Kaloriferji, stenski grelniki",
		"Kamini",
		"Solarni paneli",
	],
	"Programska oprema": ["Microsoft Windows", "Microsoft Office"],
	Powerline: ["Home Plug PowerLine"],
	"NAS sistemi": ["NAS naprave", "NAS dodatki"],
	Hlajenje: ["Hladilniki za procesorje", "Termalne paste"],
	"Priprava kave in čaja": ["Mlinčki za kavo", "Kavni aparati"],
	"Trdi diski": ["Zunanji diski", "Zunanji SSD diski", "SSD diski"],
	"Potrošni material": ["Tonerji in črnila", "Papir"],
	"Spominske kartice in čitalci": [
		"Spominske kartice",
		"Čitalniki kartic in zaščitne škatlice",
	],
	Pomnilniki: ["Pomnilniški moduli"],
	"Opekači kruha": ["Opekači kruha, toasterji"],
	Ledomat: ["Priprava sladoleda in ledomati"],
	Tehtnice: ["Kuhinjske tehtnice"],
	"Mesoreznice in salamoreznice": ["Salamoreznice/mletje mesa"],
	Mešalniki: ["Blenderji, mešalniki", "Penilniki mleka"],
	Posoda: ["Posode za živila", "Kuhinjska posoda", "Posodice za vodo"],
	"Kuhinjski žari": ["Električne pečice, žari in grelne ploskve"],
	"Dom in vrt": [
		"Stojala za perilo in obešalniki",
		"Vrtno orodje",
		"Ročno orodje",
		"Hišni polnilci",
		"Čiščenje okolice",
		"Oprema za delavnice, skladišča",
		"Senčniki in paviljoni",
		"Oprema vrta in okolice",
	],
	"Radio in budilke": ["Radio/Gramofoni"],
	Žari: ["Kamp žari", "Žari in kurišča"],
	Kampiranje: [
		"Prenosne svetilke",
		"Termovke",
		"Kamp dodatki in ostalo",
		"Kamp hladilne skrinje in torbe",
		"Kamp svetilke in komarniki",
		"Kamp paviljoni, šotori, senčniki",
		"Kamp pohištvo",
		"Kamp ležalniki in stoli",
		"Kamp kuhinjski pripomočki",
	],
	"Brezprekinitveni napajalniki": ["Brezprekinitvena napajanja"],
};

export default elkotexCategoryMap;
