const filters = {
    /**************************************************** Računalništvo ****************************************************/
    Prenosniki: ["Proizvajalec", "Namen uporabe", "Procesor", "Velikost zaslona", "Kapaciteta diska", "Kapaciteta pomnilnika", "Operacijski sistem", "Grafična kartica"],
    "Dodatki za prenosnike": ["Proizvajalec", "Vrsta dodatka"],
    AIO: ["Proizvajalec", "Vrsta zaslona", "Procesor", "Velikost zaslona", "Ločljivost", "Kapaciteta diska", "Kapaciteta pomnilnika", "Operacijski sistem", "Grafična kartica"],
    "Namizni računalniki": ["Proizvajalec", "Procesor", "Kapaciteta diska", "Kapaciteta pomnilnika", "Operacijski sistem", "Grafična kartica"],
    Mini: ["Proizvajalec", "Procesor", "Kapaciteta diska", "Kapaciteta pomnilnika", "Operacijski sistem", "Grafična kartica"],
    "Tablični računalniki": ["Proizvajalec", "Procesor", "Velikost zaslona", "ROM", "Kapaciteta pomnilnika", "Operacijski sistem"],
    Strežniki: ["Proizvajalec", "Postavitev", "Procesor", "Kapaciteta diska", "Kapaciteta pomnilnika"],
    "NAS sistemi": ["Proizvajalec", "Postavitev", "Kapaciteta", "št. LAN priklopov", "Kapaciteta pomnilnika", "Število diskov"],
    Monitorji: ["Proizvajalec", "Osveževanje", "Matrika", "Velikost zaslona", "Ločljivost", "Vhodi", "Zvočniki", "Ukrivljen zaslon", "Format"],
    "Osnovne plošče": ["Proizvajalec", "Vrsta procesorja", "Podnožje", "Format", "Vezni nabor", "Pomnilniške reže"],
    Procesorji: ["Proizvajalec", "Procesor", "Podnožje"],
    Pomnilniki: ["Proizvajalec", "Vrsta pomnilnika", "Kapaciteta pomnilnika"],
    "Trdi diski": ["Proizvajalec", "Vrsta diska", "Kapaciteta diska", "Velikost diska", "Tip diska", "Vmesnik"],
    Ohišja: ["Proizvajalec", "Velikost", "Napajalnik"],
    Napjalniki: ["Proizvajalec", "Moč", "Modularni"],
    "Grafične kartice": ["Proizvajalec", "GPU", "Grafični procesor", "Pomnilnik"],
    "Optične enote": ["Proizvajalec", "Vrsta optične enote", "Tip optične enote"],
    "Zvočne kartice": ["Proizvajalec"],
    Hlajenje: ["Proizvajalec", "Vrsta hlajenja"],
    "Usmerjevalniki, stikala in AP": ["Proizvajalec", "Vrsta", "Hitrost", "št. LAN priklopov"],
    "Mrežne kartice, antene, WIFI ojačevalci": ["Proizvajalec", "Vrsta", "Hitrost", "Vrsta povezave"],
    "Powerline": ["Proizvajalec", "št. LAN priklopov", "Hitrost"],
    Tiskalniki: ["Proizvajalec", "Vrsta tiskalnika", "Tehnologija tiska", "Ločljivost tiska", "Barva tiska", "Povezava tiskalnik", "Format"],
    "Optični bralniki": ["Proizvajalec", "Tip bralnika", "Hitrost branja", "Povezava", "Duplex", "Format"],
    "POS in dodatki": ["Proizvajalec", "Vrsta"],
    "Potrošni material": ["Proizvajalec", "Vrsta"],
    Tipkovnice: ["Proizvajalec", "Povezava", "Mehanska"],
    Miške: ["Proizvajalec", "Povezava", "Senzor", "DPI"],
    Kompleti: ["Proizvajalec", "Povezava", "Mehanska"],
    "Slušalke": ["Proizvajalec", "Povezava", "Mikrofon"],
    "Zvočniki": ["Proizvajalec", "Povezava", "Vrsta", "Sistem"],
    "Spletne kamere": ["Proizvajalec", "Ločljivost"],
    "USB ključki": ["Proizvajalec", "Kapaciteta", "Priključek"],
    "Spominske kartice in čitalci": ["Proizvajalec", "Kapaciteta", "TIP kartice", "Čitalec"],
    Mediji: ["Proizvajalec", "vrsta medija"],
    UPS: ["Proizvajalec", "Postavitev",	"Moč", "Proizvajalec"],
    Konzole: ["Proizvajalec"],
    Igre: ["Vrsta konzole"],
    "Igralni pripomočki": ["Vrsta pripomočka"],
    /**************************************************** Zvok in slika ****************************************************/
    "Televizije": ["Proizvajalec", "Diagonala", "Ločljivost", "Smart TV", "Operacijski sistem", "Vrsta zaslona"],
    Fotoaparati: ["Proizvajalec", "Vrsta"],
    "Radio in budilke": ["Proizvajalec", "Vrsta"],
    "HI-FI in Prenosni zvočniki": ["Proizvajalec", "Vrsta", "Moč", "Priključki"],
    "Domači kino": ["Proizvajalec", "Moč", "Povezljivost"],
    "Snemalniki": ["Proizvajalec"],
    "Kamere": ["Proizvajalec"],
    "Domofoni": ["Proizvajalec"],
    "Monitorji": ["Proizvajalec"],
    "Nosilci in napajalniki": ["Proizvajalec"],
    "Projektorji": ["Proizvajalec", "Namen", "Tehnologija", "Ločljivost", "Svetilnost", "Kontrast"],
    "Projekcijska platna": ["Proizvajalec", "Vrsta", "Format"],
    "Nosilci za projektorje": ["Proizvajalec", "Vrsta"],
    "Žarnice za projektorje": ["Proizvajalec"],
    /***************************************************** bela tehnika ****************************************************/
    "Pralni stroji": ["Proizvajalec", "Kapaciteta", "Energijski razred", "Polnjenje", "št. Obratov centrifuge", "inverter motor"],
    "Sušilni stroji": ["Proizvajalec", "Kapaciteta", "Energijski razred", "toplotna črpalka", "inverter motor", "samočistilni kondenzator"],
    "Pralno sušilni stroji": ["Proizvajalec", "Kapaciteta", "Energijski razred", "centrifuga", "toplotna črpalka"],
    "Pomivalni stroji": ["Proizvajalec", "Tip", "Število pogrinjkov", "višina", "Aqua Stop", "Tretja košara", "Širina", "Inverter motor", "Energijski razred"],
    "Hladilniki": ["Proizvajalec", "Tip", "Vrsta", "Energijski razred", "No frost", "višina", "širina", "položaj zamrzovalnika", "število vrat"],
    "Zamrzovalniki": ["Proizvajalec", "Tip", "Prostornina", "Energijski razred", "No frost", "višina", "širina"],
    "Pečice": ["Proizvajalec", "Tip", "čiščenje", "Energijski razred", "Prostornina", "višina"],
    "Kuhališča": ["Proizvajalec", "Tip", "vrsta okvirja", "št. Kuhališč", "širina"],
    "Kuhalni seti": ["Proizvajalec"],
    "Štedilniki": ["Proizvajalec", "Tip", "Plošč", "Prostornina", "Širina"],
    "Nape": ["Proizvajalec", "tip", "širina", "pretok", "Energijski razred"],
    /********************************************** Mali gospodinjski aparati *************************************************/
    // "Mikrovalovne pečice": ["Proizvajalec", "volumen", "žar"],
    // "Mesoreznice in salamoreznice": ["Proizvajalec"],
    // "Cvrtniki": ["Proizvajalec"],
    // "Kuhalniki": ["Proizvajalec"],
    // "Grelniki vode": ["Proizvajalec"],
    // "Kuhinjski roboti": ["Proizvajalec", "moč", "litraža"],
    // "Kuhinjski žari": ["Proizvajalec"],
    // "Mešalniki": ["Proizvajalec"],
    // "Opekači kruha": ["Proizvajalec"],
    // "Sokovniki in ožemalniki": ["Proizvajalec"],
    // "Aparati za peko kruha": ["Proizvajalec"],
    // "Vakumski aparati": ["Proizvajalec"],
    // "Multipraktiki": ["Proizvajalec"],
    // "Priprava kave in čaja": ["Proizvajalec"],
    // "Sušilci sadja": ["Proizvajalec"],
    // "Posoda": ["Proizvajalec"],
    // "Prenosna kuhališča": ["Proizvajalec"],
    // "Ledomat": ["Proizvajalec"],
    // "Tehtnice": ["Proizvajalec"],
    // "Likalniki": ["Proizvajalec"],
    // "Sesalniki": ["Proizvajalec", "vrsta", "vhodna moč", "mokro sesanje"],

}

console.table(filters);